# Font
font_family      JetBrainsMono Nerd Font
font_size        13.0

# Window
window_padding_width 8
confirm_os_window_close 0
background_opacity 1.0

# Kanagawa Dragon theme colors
foreground              #c5c9c5
background              #181616
selection_foreground    #c8c093
selection_background    #2d4f67

cursor                  #c8c093
cursor_text_color       #181616

# black
color0  #0d0c0c
color8  #a6a69c

# red
color1  #c4746e
color9  #e46876

# green
color2  #8a9a7b
color10 #87a987

# yellow
color3  #c4b28a
color11 #e6c384

# blue
color4  #8ba4b0
color12 #7fb4ca

# magenta
color5  #a292a3
color13 #938aa9

# cyan
color6  #8ea4a2
color14 #7aa89f

# white
color7  #c8c093
color15 #c5c9c5

# Tab bar
active_tab_foreground   #181616
active_tab_background   #c4b28a
inactive_tab_foreground #c5c9c5
inactive_tab_background #121010
tab_bar_background      #0d0c0c

# URL
url_color #72a7bc
